/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto_agenda.interfaces.compromisso_acoes;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projeto_agenda.classes.compromisso;
import projeto_agenda.classes.controle_listas;

/**
 *
 * @author arthur
 */
public class compromisso_adicionar extends javax.swing.JFrame {

    /**
     * Creates new form compromisso_adicionar
     */
    public compromisso_adicionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextField_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextField_datahorario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextField_descricao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextField_Local = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextField_prioridade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Botao_adicionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("nome");

        jLabel2.setText("Data/Horario");

        jLabel3.setText("Descrição");

        jLabel4.setText("Local");

        jLabel5.setText("Prioridade");

        jLabel6.setText("Lista dos envolvidos:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Botao_adicionar.setText("adicionar");
        Botao_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_adicionarActionPerformed(evt);
            }
        });

        jButton1.setText("atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(TextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(TextField_datahorario))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextField_descricao))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextField_Local))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TextField_prioridade)))
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Botao_adicionar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_datahorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextField_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(TextField_Local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextField_prioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_adicionar)
                    .addComponent(jButton1))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Botao_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_adicionarActionPerformed
        if (validarDados() == true){
            compromisso comp = new compromisso();
            comp.nome = TextField_nome.getText();
            comp.datahorario = TextField_datahorario.getText();
            comp.descricao = TextField_descricao.getText();
            comp.local = TextField_Local.getText();
            comp.prioridade = Integer.parseInt(TextField_prioridade.getText());
             int[] linhasSelecionadas = jTable1.getSelectedRows();
            String[] envolvidos = new String[linhasSelecionadas.length];
            DefaultTableModel tabela = (DefaultTableModel) jTable1.getModel();
            for (int i = 0;i<envolvidos.length;i++){
                envolvidos[i] = tabela.getValueAt(linhasSelecionadas[i], 0).toString();
            }
            comp.listaenvolvidos = envolvidos;

            controle_listas.comp.add(comp);
            TextField_Local.setText("");
            TextField_datahorario.setText("");
            TextField_descricao.setText("");
            TextField_nome.setText("");
            TextField_prioridade.setText("");
        }
    }//GEN-LAST:event_Botao_adicionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // botão atualizar
        DefaultTableModel tabela = (DefaultTableModel) jTable1.getModel();
        tabela.setRowCount(0);
        if (controle_listas.cont.size()>0){
            for (int i = 0; i < controle_listas.cont.size(); i++) {
                Object[] novaLinha = {
                    controle_listas.cont.get(i).nome,
                    controle_listas.cont.get(i).telefone
                };
                tabela.addRow(novaLinha);
                }
        }else{
            JOptionPane.showMessageDialog(null,"Lista de contatos vazia");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean validarDados(){
        if (TextField_nome.getText().matches("") || TextField_datahorario.getText().matches("") || TextField_descricao.getText().matches("") || TextField_Local.getText().matches("") || TextField_prioridade.getText().matches("")){
            JOptionPane.showMessageDialog(null,"Algum dado faltando");
            return false;
        }
        int[] linhasSelecionadas = jTable1.getSelectedRows();
        if (linhasSelecionadas.length<1){
            JOptionPane.showMessageDialog(null,"Não tem seleção na lista de envolvidos");
            return false;
        }
        try{
            int n = Integer.parseInt(TextField_prioridade.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Prioridade não é um inteiro");
            return false;
        }
        int l = controle_listas.comp.size();
        for (int i =0;i<l;i++){
            if (controle_listas.comp.get(i).datahorario.matches(TextField_datahorario.getText())){
                JOptionPane.showMessageDialog(null,"Já tem um compromisso nesta data");
                return false;
            }
        }
        JOptionPane.showMessageDialog(null,"Inserção feita!");
        return true;
    }//fim da função verificando dados para adicionar
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compromisso_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compromisso_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compromisso_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compromisso_adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compromisso_adicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_adicionar;
    private javax.swing.JTextField TextField_Local;
    private javax.swing.JTextField TextField_datahorario;
    private javax.swing.JTextField TextField_descricao;
    private javax.swing.JTextField TextField_nome;
    private javax.swing.JTextField TextField_prioridade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
